### ISSUE TITLE
Integration broken with current sonyapilib

### ISSUE THREAD

**Issue by alexmohr** [alexmohr/media_player.sony#2] opened 2019-10-07 14:55 UTC
````
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 788, in async_volume_down
    await self.hass.async_add_job(self.volume_down)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sony/media_player.py", line 298, in volume_down
    self.sonydevice.volume_down()
AttributeError: 'SonyDevice' object has no attribute 'volume_down'

````

ToDo:
* merge https://github.com/alexmohr/sonyapilib/pull/40
* Update version and push to pip

@patrul @ptimatth

**Comment by alexmohr** [comment] 2019-10-07 15:03
https://github.com/alexmohr/media_player.sony/pull/1 Must be merged again when this issue is solved. 

Merging can be done by reverting this PR https://github.com/alexmohr/media_player.sony/pull/3

**Comment by patrul** [comment] 2019-10-07 20:40
Great, great!
volume_up and volume_down works for me but mute is still giving error

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 373, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sony/media_player.py", line 302, in mute_volume
    self.sonydevice.mute_volume()
AttributeError: 'SonyDevice' object has no attribute 'mute_volume'

```

Do not know it this makes sense, but I get this error also. Not sure if it is new, I guess it was with previous version

```
2019-10-07 22:27:46 ERROR (SyncWorker_9) [sonyapilib.device] HTTPError: 403 Client Error: Forbidden for url: http://192.168.1.31:50002/getRemoteCommandList
2019-10-07 22:27:46 ERROR (SyncWorker_9) [custom_components.sony.media_player] 9830
2019-10-07 22:27:46 ERROR (SyncWorker_9) [custom_components.sony.media_player] Amplificador
```

**Comment by alexmohr** [comment] 2019-10-07 20:53
Can you make sure you are using the current version from master, because mute_volume has been changed to mute

**Comment by patrul** [comment] 2019-10-07 20:59
Yes, I installed last versión

```
bash-5.0# pip install sonyapilib
Requirement already satisfied: sonyapilib in /usr/local/lib/python3.7/site-packages (0.4.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from sonyapilib) (2.22.0)
Requirement already satisfied: wakeonlan in /usr/local/lib/python3.7/site-packages (from sonyapilib) (1.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from sonyapilib) (41.0.1)
Requirement already satisfied: jsonpickle in /usr/local/lib/python3.7/site-packages (from sonyapilib) (1.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->sonyapilib) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->sonyapilib) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->sonyapilib) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->sonyapilib) (1.25.3)
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by alexmohr** [comment] 2019-10-07 21:00
Oh sorry I meant the lastest version of this component. At the moment the auto updater is not working as it is documented in the readme. I am currently working on it.

**Comment by ptimatth** [comment] 2019-10-07 21:03
I have found some merging issue here 
https://github.com/alexmohr/media_player.sony/commit/6ed4d300c521806cc22b4442dc0f49bc188e11d0
I have tested my latest version of media player and it work

**Comment by patrul** [comment] 2019-10-07 21:07
I am sorry, I have just installed again.

No volume control on this version.

When I switch on this media player, it gives me this error, but it starts

`2019-10-07 23:08:50 ERROR (SyncWorker_18) [sonyapilib.device] HTTPError: HTTPConnectionPool(host='192.168.1.31', port=50001): Max retries exceeded with url: /upnp/control/IRCC (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xae17a190>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by ptimatth** [comment] 2019-10-07 21:10
> I have found some merging issue here
> [6ed4d30](https://github.com/alexmohr/media_player.sony/commit/6ed4d300c521806cc22b4442dc0f49bc188e11d0)
> I have tested my latest version of media player and it work

My bad, it's me, i have mist-merged here 93e8c4a5e195dbccba3bd4f1f579f824c235eeeb

**Comment by ptimatth** [comment] 2019-10-07 21:23
@patrul, @alexmohr work on it ;)

**Comment by ptimatth** [comment] 2019-10-07 21:26
Tested and work for me.

**Closed as completed** 2019-10-07 21:26 UTC
Labels: bug

**Comment by patrul** [comment] 2019-10-08 07:32
It works also for me. I do not why, but when I use the power button of the media player, it goes to HOME option, similar to config screen and not able to play directly from last input selected before switching off, for example TV input.

If I use the power button of remote, it works and TV input is selected by default.
